services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ../..:/workspaces:cached
    networks:
      - shared_network

    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

networks:
  shared_network:
    driver: bridge
